---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Un-block distractions
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: ""
      become: yes

