---
- hosts: localhost
  tasks:
    - name: Block distractions
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          127.0.0.1   www.facebook.com
          127.0.0.1   twitter.com
          127.0.0.1   tweetdeck.twitter.com
          127.0.0.1   www.ebay.co.uk
          127.0.0.1   strava.com
          127.0.0.1   news.bbc.co.uk
          127.0.0.1   www.bbc.co.uk
          127.0.0.1   youtube.com
          127.0.0.1   www.youtube.com
          127.0.0.1   instagram.com
          127.0.0.1   guardian.com
          127.0.0.1   guardian.co.uk

